# .github/workflows/ci.yml
name: C++ CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev

    - name: Configure CMake
      run: cmake -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      working-directory: ./build
      run: ctest -C Debug --output-on-failure
